version: '3'
services:
  # Define the app service
  app:
    build: .
    ports:
      - "5000:5000"  
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db  
      DB_USER: user  
      DB_PASSWORD: user_password  
      DB_NAME: store_db  
  
  # Define the db service
  db:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: store_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
